name: open_3d_mapper
description: Desktop application for 3D Level Design and Mapping.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.5.0
  file_picker: ^5.2.5
  path: ^1.8.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
